"""add_system_prompt

Revision ID: f3a40b5ea5ca
Revises: 64b18bb3f4ca
Create Date: 2026-03-15 18:43:11.897880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a40b5ea5ca'
down_revision: Union[str, None] = '64b18bb3f4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'system_prompt')
    # ### end Alembic commands ###
